apiVersion: v1
kind: Secret
metadata:
  name: passagens-secret
  namespace: passagens-bot
type: Opaque
stringData:
  SERPAPI_KEY: "eaefaa5d0ce74466bff7deba3bcdde70b19b5156789c89e54c6a219cf0c27e78"
  DISCORD_WEBHOOK_URL: "https://discord.com/api/webhooks/1503195521848836127/535nqvQk5N2Pw_xBqYUHFBg9NFZ8M5BllFA2HK_Zd8yRnXcSo5MdKlEGE5AB_MZAFMgY"
  WEBHOOK_MALUCOS: "https://discord.com/api/webhooks/1503517450640294011/rPlUSInLJ4SjrKC_N90nCmM9H1x-jd3hNydE-NscQgp1Lzy0ZX_k42ESolZgOH5T7l0m"
  WEBHOOK_DATAS_ESPECIFICAS: "https://discord.com/api/webhooks/1503517547956539523/E-esEWNl2RpIT70dVqY6-lhMGQSG6nK909CqWtF6Y_pgGNQCcMGLgrryoVyylgjarlnN"
  WEBHOOK_INTERNACIONAL: "https://discord.com/api/webhooks/1503517297111994418/cLAVi3TqA-dJh4gCcSrGamvcUWy6liQ2RtC9Ihods7vUiNwSdJn0-MpUiat9yECaqbar"
  WEBHOOK_BRASIL: "https://discord.com/api/webhooks/1503517405882876006/w-d7oXfisyH0H1ZG7NjDPhrf4V7sgD29Dy9TFVKMjckjm0u9Fo01eMsZ3-IkUOCjgJ8m"