apiVersion: v1
kind: Secret
metadata:
  name: discord-webhook
  namespace: passagens-bot
type: Opaque
stringData:
  DISCORD_WEBHOOK_URL: "https://discord.com/api/webhooks/1503195521848836127/535nqvQk5N2Pw_xBqYUHFBg9NFZ8M5BllFA2HK_Zd8yRnXcSo5MdKlEGE5AB_MZAFMgY"
  SERPAPI_KEY: "eaefaa5d0ce74466bff7deba3bcdde70b19b5156789c89e54c6a219cf0c27e78"