apiVersion: apps/v1
kind: Deployment
metadata:
  name: passagens-deployment
  namespace: passagens-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: passagens-bot
  template:
    metadata:
      labels:
        app: passagens-bot
    spec:
      containers:
      - name: bot-container
        image: passagens-bot:latest
        imagePullPolicy: Never
        workingDir: /app
        command: ["python", "src/bot.py"] 
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"
        env:
        - name: SERPAPI_KEY
          valueFrom:
            secretKeyRef:
              name: passagens-secret
              key: SERPAPI_KEY
        - name: DISCORD_WEBHOOK_URL
          valueFrom:
            secretKeyRef:
              name: passagens-secret
              key: DISCORD_WEBHOOK_URL
        - name: WEBHOOK_BRASIL
          valueFrom:
            secretKeyRef:
              name: passagens-secret
              key: WEBHOOK_BRASIL
        - name: WEBHOOK_INTERNACIONAL
          valueFrom:
            secretKeyRef:
              name: passagens-secret
              key: WEBHOOK_INTERNACIONAL
        - name: WEBHOOK_MALUCOS
          valueFrom:
            secretKeyRef:
              name: passagens-secret
              key: WEBHOOK_MALUCOS
        - name: WEBHOOK_DATAS_ESPECIFICAS
          valueFrom:
            secretKeyRef:
              name: passagens-secret
              key: WEBHOOK_DATAS_ESPECIFICAS