apiVersion: apps/v1
kind: Deployment
metadata:
  name: passagens-deployment
  namespace: passagens-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: passagens-bot
  template:
    metadata:
      labels:
        app: passagens-bot
    spec:
      containers:
      - name: bot-container
        image: passagens-bot:latest
        imagePullPolicy: Never
        workingDir: /app
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"
        env:
        - name: SERPAPI_KEY
          valueFrom:
            secretKeyRef:
              name: passagens-secret
              key: SERPAPI_KEY # Ajustado para bater com seu 02-secret.yaml
        - name: DISCORD_WEBHOOK_URL
          valueFrom:
            secretKeyRef:
              name: passagens-secret
              key: DISCORD_WEBHOOK_URL # Ajustado para bater com seu 02-secret.yaml
        envFrom:
        - configMapRef:
            name: bot-config
        volumeMounts:
        - name: data
          mountPath: /app/data
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: bot-storage # Garanta que o 03-pvc.yaml já foi aplicado