replicaCount: 1

image:
  repository: passagens-bot
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: ClusterIP
  port: 80
secret:
  serpApiKey: "eaefaa5d0ce74466bff7deba3bcdde70b19b5156789c89e54c6a219cf0c27e78"
  webhooks:
    internacional: "https://discord.com/api/webhooks/1503517297111994418/cLAVi3TqA-dJh4gCcSrGamvcUWy6liQ2RtC9Ihods7vUiNwSdJn0-MpUiat9yECaqbar"
    brasil: "https://discord.com/api/webhooks/1503517405882876006/w-d7oXfisyH0H1ZG7NjDPhrf4V7sgD29Dy9TFVKMjckjm0u9Fo01eMsZ3-IkUOCjgJ8m"
    voos_malucos: "https://discord.com/api/webhooks/1503517450640294011/rPlUSInLJ4SjrKC_N90nCmM9H1x-jd3hNydE-NscQgp1Lzy0ZX_k42ESolZgOH5T7l0m"
    datas_especificas: "https://discord.com/api/webhooks/1503517547956539523/E-esEWNl2RpIT70dVqY6-lhMGQSG6nK909CqWtF6Y_pgGNQCcMGLgrryoVyylgjarlnN"

config:
  intervaloHoras: 1
  debug: "True"