apiVersion: v1
kind: ConfigMap
metadata:
  name: bot-config
  namespace: passagens-bot
data:
  config.py: |
    # Configurações do Bot via Helm
    DEBUG = True
---
apiVersion: v1
kind: Secret
metadata:
  name: passagens-secret
  namespace: passagens-bot
type: Opaque
stringData:
  DISCORD_WEBHOOK_URL: {{ .Values.secret.discordWebhookUrl | quote }}
  SERPAPI_KEY: {{ .Values.secret.serpApiKey | quote }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: passagens-pvc
  namespace: passagens-bot
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi