apiVersion: apps/v1
kind: Deployment
metadata:
  name: passagens-deployment
  namespace: passagens-bot
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: passagens-bot
  template:
    metadata:
      labels:
        app: passagens-bot
    spec:
      containers:
        - name: passagens-bot
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            # Chave da API
            - name: SERPAPI_KEY
              valueFrom:
                secretKeyRef:
                  name: passagens-secret
                  key: serpApiKey
           
            - name: WEBHOOK_INTERNACIONAL
              valueFrom:
                secretKeyRef:
                  name: passagens-secret
                  key: internacional
            - name: WEBHOOK_BRASIL
              valueFrom:
                secretKeyRef:
                  name: passagens-secret
                  key: brasil
            - name: WEBHOOK_MALUCOS
              valueFrom:
                secretKeyRef:
                  name: passagens-secret
                  key: voos_malucos
            - name: WEBHOOK_DATAS
              valueFrom:
                secretKeyRef:
                  name: passagens-secret
                  key: datas_especificas
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"