name: Deploy Passagens Bot

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write 

    steps:
      - name: Checkout do Código
        uses: actions/checkout@v4

      - name: Configurar Helm
        uses: azure/setup-helm@v4.2.0

      - name: Validar Helm Chart (Lint)
        run: helm lint ./helm/passagens-bot/

      - name: Login no GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push da Imagem Real
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/startdevopss/passagens-bot:latest
            ghcr.io/startdevopss/passagens-bot:${{ github.sha }}