name: Deploy Passagens Bot

# O pipeline roda sempre que você envia código para a branch 'main'
on:
  push:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do Código
        uses: actions/checkout@v4

      - name: Configurar Helm
        uses: azure/setup-helm@v4.2.0

      - name: Validar Helm Chart (Lint)
        run: helm lint ./helm/passagens-bot/

      - name: Simular Build do Docker
        run: docker build -t passagens-bot:latest .

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure kubeconfig
        run: |
          echo "${{ secrets.KUBECONFIG_BASE64 }}" | base64 -d > $HOME/.kube/config

      - name: Deploy updated image
        run: |
          kubectl set image deployment/passagens-bot passagens-bot=ghcr.io/startdevopss/passagens-bot:${{ github.sha }}
          kubectl rollout status deployment/passagens-bot
